mask_site/database/models.py
"""from mask_site import db
from datetime import datetime

class order(db.Model):
    _id = db.Column("id", db.Integer, primary_key=True)
    name = db.Column("name", db.String(20))
    surname = db.Column("surname", db.String(20))
    email = db.Column("email", db.String(120))
    address = db.Column("address",db.String(60))
    address_2 = db.Column("address_2",db.String(60))
    post_code = db.Column("post_code",db.String(60))
    quantity = db.Column("quantity",db.String(10))
    date_posted = db.Column(db.DateTime, nullable=False,
        default=datetime.utcnow)

    def __init__(self, name, surname, email, address, address_2, post_code, quantity):
        self.name = name
        self.surname = surname
        self.email = email
        self.address = address
        self.address_2 = address_2
        self.post_code = post_code
        self.quantity = quantity
        """

mask_site/emails_package/forms.py
from flask_wtf import FlaskForm, RecaptchaField
from wtforms import StringField, IntegerField, SubmitField, SelectField
from wtforms.validators import DataRequired, Length, Email


class RegistrationForm(FlaskForm):
    name = StringField('Imię', validators=[
                       DataRequired(), Length(min=2, max=30)])
    surname = StringField('Nazwisko', validators=[
                          DataRequired(), Length(min=2, max=30)])
    email = StringField('Email', validators=[
                        DataRequired(), Email(), Length(min=2, max=120)])
    address = StringField('Ulica, numer mieszkania', validators=[
                          DataRequired(), Length(min=2, max=45)])
    address_2 = StringField('Miejscowość', validators=[
                            DataRequired(), Length(min=2, max=45)])
    post_code = StringField('Kod Pocztowy', validators=[
                            DataRequired(), Length(min=2, max=10)])
    quantity = SelectField('Ilość', [DataRequired()],
                        choices=[('1', '1'),
                                 ('2', '2'),
                                 ('3', '3'),
                                 ('4', '4'),
                                 ('5', '5'),
                                 ('6', '6')])
    recaptcha = RecaptchaField()
    submit = SubmitField('Wyślij')



"""
   def validate_email(self, email):
       duplicate = dublicate.query.filter_by(email=email.data).first()
        if user:
            raise ValidationError('That email is taken. Please choose a different one.')
"""

mask_site/__init__.py
from flask import Flask
#from flask_sqlalchemy import SQLAlchemy
from flask_mail import Mail
from flask_wtf.csrf import CSRFProtect
from mask_site.config import Config


csrf = CSRFProtect()
mail = Mail()



def create_app(config_class=Config):
    app = Flask(__name__)
    app.config.from_object(Config)
    csrf.init_app(app)
    mail.init_app(app)
    from mask_site.main.routes import main
    from mask_site.emails_package.routes import customers
    from mask_site.errors.handlers import errors
    app.register_blueprint(main)
    app.register_blueprint(customers)
    app.register_blueprint(errors)

    return app

mask_site/emails_package/routes.py
from flask import Blueprint, redirect, render_template, request, session, flash, url_for, current_app
from flask_wtf.csrf import CSRFError
from mask_site.emails_package.forms import RegistrationForm
from mask_site.emails_package.emails import email_form


customers = Blueprint('customers', __name__)



@customers.route("/register", methods=["GET", "POST"])
def register():
    form = RegistrationForm()
    if form.validate_on_submit():
        """
        ord = order(name=form.name.data, surname = form.surname.data, email=form.email.data, address= form.address.data, address_2= form.address_2.data, post_code= form.post_code.data,quantity= form.quantity.data )
        db.session.add(ord)
        db.session.commit()
        """
        email_form().send_emails()
        return redirect(url_for('main.confirm'))
    return render_template('formularz.html', title='Register', form=form)
 

mask_site/main/routes.py
from flask import Blueprint, redirect, render_template, request, session, flash, url_for, current_app

main = Blueprint('main', __name__)


@main.route("/")
@main.route("/home")
def home():
    return render_template("home.html")


@main.route("/potwierdzenie")
def confirm():
    return render_template('potwierdzenie.html')



"""
@app.route("/zamowienia")
def view():
    return render_template("zamowienia.html", values=order.query.all())

"""

mask_site/templates/csrf_error.html
<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!-->
<html class="no-js">
<!--<![endif]-->

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>CSRF</title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="">
    <!-- Favicon -->
    <link rel="icon" href="{{ url_for('static', filename='images/favicon.ico')}}">
</head>

<body>
    <!--[if lt IE 7]>
            <p class="browsehappy">You are using an <strong>outdated</strong> browser. Please <a href="#">upgrade your browser</a> to improve your experience.</p>
        <![endif]-->

    <script src="" async defer></script>
</body>

</html>

mask_site/templates/erros/csrf_error.html
<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!-->
<html class="no-js">
<!--<![endif]-->

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>CSRF</title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="">
    <!-- Favicon -->
    <link rel="icon" href="{{ url_for('static', filename='images/favicon.ico')}}">
</head>

<body>
    <!--[if lt IE 7]>
            <p class="browsehappy">You are using an <strong>outdated</strong> browser. Please <a href="#">upgrade your browser</a> to improve your experience.</p>
        <![endif]-->
        <p>Cross-site request forgery, also known as one-click attack or
             session riding and abbreviated as CSRF (sometimes pronounced sea-surf) or XSRF, is a type of malicious exploit of a website where unauthorized commands are transmitted
             from a user that the web application trusts.</p>

             <h2>Please don't do that..</h2>
             <p>If you thing the error is on our site, please contact us </p>

    <script src="" async defer></script>
</body>

</html>

mask_site/templates/formularz.html
<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!-->
<html class="no-js">
<!--<![endif]-->

<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>Formularz</title>
  <meta name="description" content="">
  <meta name="viewport" content="width=device-width, initial-scale=1">


  <!-- Google Fonts -->
  <link href="https://fonts.googleapis.com/css?family=Montserrat|Open+Sans|Ubuntu&display=swap" rel="stylesheet">

  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
    integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
  <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='styles-formularz.css') }}">
  <!-- Bootstrap Scripts -->
  <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js"
    integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n"
    crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
    integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
    crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
    integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6"
    crossorigin="anonymous"></script>
  <!-- Favicon -->
  <link rel="icon" href="{{ url_for('static', filename='images/favicon.ico')}}">
</head>

<body>

  <section id="title-formula">

    <!-- Nav Bar -->
    <div class="container-fluid">
      <nav class="navbar navbar-expand-lg navbar-dark">
        <a class="navbar-brand" href="{{ url_for('main.home') }}">Maska dla seniora</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
          aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav ml-auto">
            <li class="nav-item">
              <a class="nav-link" href="{{ url_for('main.home') }}">Strona główna</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{{ url_for('customers.register') }}">Formularz</a>
            </li>
          </ul>
        </div>
      </nav>
    </div>
  </section>

  <div class="formularz-text">
    <h2>Wypełnij formularz, abyśmy mogli dostarczyć maski!</h2>
    <p>Wpisz dane osoby, która Twoim zdaniem potrzebuje maski ochronnej w czasie epidemii COVID-19.</p>
    <p>Doceniamy twoje starania i chęć pomocy.</p>
    Inni też to docenią.
    </p>
  </div>


  <div class="formularz">
    <form method="POST" action="">
      {{ form.csrf_token }}
      {{ form.hidden_tag()  }}
      <fieldset class="form-group">
        <legend class="border=bottom mb-4">Wypełnij formularz</legend>
        <div class="form-group">
          {{form.name.label(class="form-control-label")}}
          {% if form.name.errors %}
          {{ form.name(class="form-control form-control-lg is-invalid") }}
          <div class="invalid-feedback">
            {% for error in form.name.errors %}
            <span>{{ error }}</span>
            {% endfor %}
          </div>
          {% else %}
          {{ form.name(class="form-control form-control-lg") }}
          {% endif %}
        </div>
        <div class="form-group">
          {{form.surname.label(class="form-control-label")}}
          {% if form.surname.errors %}
          {{ form.surname(class="form-control form-control-lg is-invalid") }}
          <div class="invalid-feedback">
            {% for error in form.surname.errors %}
            <span>{{ error }}</span>
            {% endfor %}
          </div>
          {% else %}
          {{ form.surname(class="form-control form-control-lg") }}
          {% endif %}
        </div>
        <div class="form-group">
          {{ form.email.label(class="form-control-label") }}
          {% if form.email.errors %}
          {{ form.email(class="form-control form-control-lg is-invalid") }}
          <div class="invalid-feedback">
            {% for error in form.email.errors %}
            <span>{{ error }}</span>
            {% endfor %}
          </div>
          {% else %}
          {{ form.email(class="form-control form-control-lg") }}
          {% endif %}
        </div>
        <div class="form-group">
          {{form.quantity.label(class="form-control-label")}}
          {{ form.quantity(class="form-control form-control-lg") }}

        </div>
        <div class="form-group">
          {{form.address.label(class="form-control-label")}}
          {% if form.address.errors %}
          {{ form.address(class="form-control form-control-lg is-invalid") }}
          <div class="invalid-feedback">
            {% for error in form.address.errors %}
            <span>{{ error }}</span>
            {% endfor %}
          </div>
          {% else %}
          {{ form.address(class="form-control form-control-lg") }}
          {% endif %}
        </div>
        <div class="form-group">
          {{form.post_code.label(class="form-control-label")}}
          {% if form.post_code.errors %}
          {{ form.post_code(class="form-control form-control-lg is-invalid") }}
          <div class="invalid-feedback">
            {% for error in form.post_code.errors %}
            <span>{{ error }}</span>
            {% endfor %}
          </div>
          {% else %}
          {{ form.post_code(class="form-control form-control-lg") }}
          {% endif %}
        </div>
        <div class="form-group">
          {{form.address_2.label(class="form-control-label")}}
          {% if form.address_2.errors %}
          {{ form.address_2(class="form-control form-control-lg is-invalid") }}
          <div class="invalid-feedback">
            {% for error in form.address_2.errors %}
            <span>{{ error }}</span>
            {% endfor %}
          </div>
          {% else %}
          {{ form.address_2(class="form-control form-control-lg") }}
          {% endif %}
        </div>
        <!-- CAPTCHA -->
        <div class="form-group">
          {{  form.recaptcha }}
          {% for error in form.recaptcha.errors %}
          <li style="color: red;">{{ error }}</li>
          {% endfor %}
        </div>
      </fieldset>
      <div class="form-group">
        {{ form.submit(class="btn btn-lg btn-outline-light")}}
      </div>

    </form>
  </div>


  <script src="" async defer></script>
</body>

</html>

mask_site/templates/home.html
<!DOCTYPE html>
<html>

<head>
  <meta charset="utf-8">

  <meta name="viewport" content="width=700, initial-scale=1">


  <!-- Google Fonts -->
  <link href="https://fonts.googleapis.com/css?family=Montserrat|Open+Sans|Ubuntu&display=swap" rel="stylesheet">

  <!-- CSS Stylesheets -->
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
    integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
  <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='styles3.css') }}">


  <!-- Font icons -->
  <script src="https://kit.fontawesome.com/bd2f6a8581.js" crossorigin="anonymous"></script>

  <!-- Bootstrap Scripts -->
  <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js"
    integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n"
    crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
    integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
    crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
    integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6"
    crossorigin="anonymous"></script>
  <!-- Favicon -->
  <link rel="icon" href="{{ url_for('static', filename='images/favicon.ico')}}">
</head>

<body>

  <section id="title">


    <div class="container-fluid">


      <!-- Nav Bar -->

      <nav class="navbar navbar-expand-lg navbar-dark">
        <a class="navbar-brand" href="{{ url_for('main.home') }}">Maska dla seniora</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
          aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav ml-auto">
            <li class="nav-item">
              <a class="nav-link" href="{{ url_for('main.home') }}">Strona główna</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{{ url_for('customers.register') }}">Formularz</a>
            </li>
          </ul>
        </div>
      </nav>


      <!-- Title -->

      <div class="row">


        <div class="col-lg-6">

          <h1>Wesprzyj akcję maska dla seniora! </h1>

          <p class="title">Dokładamy najwyższych starań, aby nasze maski były w 100% bezpieczne. Dlatego wykonujemy je
            ze starannie dobranych materiałów i gwarantujemy sterylne opakowania. </p>

            <a class="main nav-link" href="{{ url_for('customers.register') }}">Formularz</a>
        </div>
        <div class="col-lg-6">
          <image class="grands" src="{{ url_for('static', filename='images/grandparents.png') }}" alt="grands">
        </div>
      </div>
  </section>


  <!-- Features -->

  <section id="features">

    <div class="row">


      <div class="feature-box col-lg-4">
        <i class="icon fas fa-check-circle fa-4x"></i>
        <h3>Zgodne z wytycznymi</h3>
        <p class="features-p">Spełniają warunki sanepidu</p>
      </div>

      <div class="feature-box col-lg-4">
        <i class="icon fas fa-heart fa-4x"></i>
        <h3> Wielokrotnego użytku </h3>
        <p class="features-p">Zrobione z kieszonką na filtr</p>
      </div>

      <div class="feature-box col-lg-4">
        <i class="icon fas fa-map-marked fa-4x"></i>
        <h3>Bezkontaktowa wysyłka</h3>
        <p class="features-p-third">Odbierz maskę w paczkomacie</p>
      </div>

    </div>
  </section>

  <!-- Carousel section -->

  <section id="Carousel-purpose">

    <div id="Carousel" class="carousel slide" data-ride="carousel">
      <ol class="carousel-indicators">
        <li data-target="#Carousel-purpose" data-slide-to="0" class="active"></li>
        <li data-target="#Carousel-purpose" data-slide-to="1"></li>
      </ol>
      <div class="carousel-inner">
        <div class="carousel-item active" data-interval="3000">
          <h3>Szyjemy maski dla najbardziej potrzebujących oraz domów opieki.</h3>
          <img src="{{ url_for('static', filename='images/hospital.png') }}" width="100px" height="100px">
        </div>
        <div class="carousel-item" data-interval="3000">
          <h3>Wypełnij formularz, by pomóc nam dostarczyć maski dla potrzebujących!</h3>

          <br>
          <a class="main2 nav-link" href="{{ url_for('customers.register') }}">Formularz</a>
          <br>
          <br>
        </div>

      </div>
      <a class="carousel-control-prev" href="#Carousel-purpose" role="button" data-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
      </a>
      <a class="carousel-control-next" href="#Carousel-purpose" role="button" data-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
      </a>
    </div>
  </section>


  <!-- Pomoc -->
  <section id="help">
    <h2 class="helpus">Możesz nam pomóc na 3 sposoby:</h2>

    <div class="row">


      <div class="feature-box col-lg-4">
        <img class="donate" src="{{ url_for('static', filename='images/donate.png') }}" width="100px" height="100px">
        <h3>Przekazać maseczki</h3>
      </div>

      <div class="feature-box col-lg-4">
        <img class="help" src="{{ url_for('static', filename='images/help.png') }}" width="100px" height="100px">
        <h3> Przyłaczyć się do szycia </h3>

      </div>

      <div class="feature-box col-lg-4">
        <img class="fabric" src="{{ url_for('static', filename='images/fabric.png') }}" width="100px" height="100px">
        <h3>Zdobyć dla nas materiał</h3>
        </div>
      
      <p class="mail-p">Pytania prosimy kierować na adres: <span class="mail">maskadlaseniora@gmail.com</span></p>
  
  </section>

  <!-- Footer -->

  <footer id="footer">
    <div class="container-fluid">

      <a href="https://www.facebook.com/Maska-dla-seniora-101866628160951/"><img class="social-icon" src="{{ url_for('static', filename='images/facebook.svg') }}" ></a>
      <a href="https://instagram.com/maska_dla_seniora?igshid=1uv9m07jsai9j"><img class="social-icon" src="{{ url_for('static', filename='images/instagram.svg') }}"></a>

      <p>© Copyright 2020 Maska dla seniora</p>


    </div>


  </footer>


</body>

</html>

mask_site/templates/potwierdzenie.html
<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!-->
<html class="no-js">
<!--<![endif]-->

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Potwierdzenie</title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Google Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Montserrat|Open+Sans|Ubuntu&display=swap" rel="stylesheet">
    <!-- CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
        integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='styles-thanks.css') }}">
    <!-- Bootstrap-->
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js"
        integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
        integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
        crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
        integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6"
        crossorigin="anonymous"></script>
    <!-- Favicon -->
    <link rel="icon" href="{{ url_for('static', filename='images/favicon.ico')}}">

</head>

<body>

    <section id="title-thanks">
        <!-- Nav Bar -->
        <div class="container-fluid">
            <nav class="navbar navbar-expand-lg navbar-dark">
                <a class="navbar-brand" href="{{ url_for('main.home') }}">Maska dla seniora</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse"
                    data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false"
                    aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav ml-auto">
                        <li class="nav-item">
                            <a class="nav-link" href="{{ url_for('main.home') }}">Strona główna</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{{ url_for('customers.register') }}">Formularz</a>
                        </li>
                    </ul>
                </div>
            </nav>

        </div>


        <h1>Dziękujemy za zgłoszenie!</h1>

        <p>W tym momencie twoje zamówienie jest w trakcie realizacji i niebawem trafi do rąk osoby, o którą zdecydowałeś
            się zatroszczyć!</p>

        <div><iframe src="https://giphy.com/embed/kGRS5hhxqJ0xOsZti7" frameBorder="0" class="giphy-embed"
                allowFullScreen></iframe></div>
        <p><a href="https://giphy.com/stickers/stay-home-stayhome-at-kGRS5hhxqJ0xOsZti7"></a></p>
    </section>

    <footer id="footer">
        <div class="container-fluid">

            <a href="https://www.facebook.com/Maska-dla-seniora-101866628160951/"><img class="social-icon" src="{{ url_for('static', filename='images/facebook.svg') }}" ></a>
            <a href="https://instagram.com/maska_dla_seniora?igshid=1uv9m07jsai9j"><img class="social-icon" src="{{ url_for('static', filename='images/instagram.svg') }}"></a>
      
            <p>© Copyright 2020 Maska dla seniora</p>
        </div>


    </footer>

    <script src="" async defer></script>
</body>

</html>

mask_site/templates/zamowienia.html
<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!-->
<html class="no-js">
<!--<![endif]-->

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title></title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="">
    <!-- Favicon -->
    <link rel="icon" href="{{ url_for('static', filename='images/favicon.ico')}}">
</head>

<body>
    <h1>Maska dla seniora</h1>
    <br>
    <!--[if lt IE 7]>
            <p class="browsehappy">You are using an <strong>outdated</strong> browser. Please <a href="#">upgrade your browser</a> to improve your experience.</p>
        <![endif]-->
    {% for item in values %}
    <br>
    <h2>Name: {{item.name}},
        Surname: {{item.surname}},
        Emails: {{item.email}},
        Address: {{item.addres}},
        Address_2: {{item.address_2}},
        Post Code: {{item.post_code}},
        Quantity: {{item.quantity}},
        Date: {{item.date_posted}}</h2>
    <br>
    {% endfor %}
    <script src="" async defer></script>
</body>

</html>